FirstProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('myapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #yangi qo'shildi

myapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('',views.home,name="home-page"),
    path('articles/',views.main,name="articles-list"),
    path('articles/create/',views.create_article,name="create-article"),
    path('articles/<int:id>/',views.article_detail,name="article-detail"),

] 

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):

    title = models.CharField(max_length=200)
    description = models.TextField()
    is_active = models.BooleanField(default=False)
    image = models.ImageField(upload_to="Article/image")
    create_data = models.DateTimeField(auto_now=True)
    #4ta maydon qo'shish
    def __str__(self) -> str:
        return f"{self.title}"

class Comment(models.Model):
    first_name = models.CharField(max_length=50)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(default=3)

    article = models.ForeignKey(Article,on_delete=models.CASCADE)

myapp/forms.py
from django import forms

class ArticleForm(forms.Form):
    title = forms.CharField(max_length=200)
    description = forms.CharField(
     widget=forms.Textarea(attrs={'placeholder': 'Maqola matnini kiriting'}))
    image = forms.ImageField()

class CommentForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    text = forms.CharField(max_length=200)

myapp/views.py
from django.shortcuts import render

from django.shortcuts import render

# home_view,about_view,chocolate_view,contact_view

def home_view(request):
    return render(request,"index.html")

def about_view(request):
    return render(request,"about.html")

def dukon_view(request):
    return render(request,"product.html")

def contact_view(request):
    return render(request,"contact.html")



from django.shortcuts import render,HttpResponseRedirect
#300,301,302
from .models import Article,Comment
from django.contrib import messages  # new
from django.urls import reverse  # new

from .forms import ArticleForm,CommentForm


def home(request):
    articles = Article.objects.filter(is_active=True).order_by("-id")[:3]
    context = {"articles":articles}
    return render(request,"about.html",context)

def main(request):
    articles = Article.objects.filter(is_active=True).order_by("-id")
    context = {"articles":articles}
    return render(request,"index.html",context)


def main(request):
    articles = Article.objects.filter(is_active=True).order_by("-id")
    context = {"articles":articles}
    return render(request,"contact.html",context)

def main(request):
    articles = Article.objects.filter(is_active=True).order_by("-id")
    context = {"articles":articles}
    return render(request,"product.html",context)


def main(request):
    articles = Article.objects.filter(is_active=True).order_by("-id")
    context = {"articles":articles}
    return render(request,"testimonial.html",context)




def article_detail(request,id):
    article = Article.objects.get(id=id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            first_name = form.data["first_name"]
            text = form.data["text"]
        
            comment = Comment(
                first_name=first_name,
                text=text,
                article=article
            )
            comment.save()
            messages.success(request, 'Izoh yuborildi')


    
    comments = Comment.objects.filter(article=id)
    form = CommentForm()
    context = {"about":article,"comments":comments,"form":form}
    return render(request,"about.html",context)


def create_article(request):

    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            image = form.cleaned_data['image']

            article = Article(
                title=title,
                description=description,
                image=image,
            )
            article.save()
            messages.success(request, '🥳 Maqolangiz adminga yuborildi, tekshiruvdan so\'ng chop etiladi')
            return HttpResponseRedirect(reverse('articles-list'))
        else:
            messages.error(request, 'Formani qaytadan to\'ldiring')
    else:
        form = ArticleForm()
    context = {"form": form}
    
    return render(request, "create_article.html", context)

templates/article.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{{ article.title }}</title>
    <style>

        .rating-stars input[type="radio"] {
            display: none; /* Hide the actual radio buttons */
        }
        
        .rating-stars label {
            font-size: 0; /* Hide the text label */
            cursor: pointer;
        }
        
        .rating-stars label:before {
            content: '\2605'; /* Unicode character for a star */
            font-size: 30px; /* Adjust the size of the star */
            color: #ffcc00; /* Default color of the unchecked stars */
        }
        
        .rating-stars input[type="radio"]:checked ~ input[type="radio"] + label:before {
            color: #ccc; /* Color of the checked stars and stars before it */
        }
        
        /* Custom styles for better layout */
        body {
            background-color: #f8f9fa; /* Set background color */
            padding: 20px; /* Add padding for better spacing */
        }
        .article-container {
            max-width: 800px; /* Limit content width */
            margin: 0 auto; /* Center content */
            background-color: #fff; /* Set background color for article container */
            padding: 20px; /* Add padding */
            border-radius: 10px; /* Add border radius for rounded corners */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add box shadow for depth */
        }
        .article-title {
            font-size: 24px; /* Set title font size */
            color: #333; /* Set title color */
        }
        .article-description {
            font-size: 18px; /* Set description font size */
            color: #555; /* Set description color */
        }
        .article-meta {
            font-size: 16px;
            color: #777;
            margin-bottom: 10px;
        }
        .back-button {
            margin-top: 20px; /* Add margin on top of button */
        }
    </style>
</head>
<body>
    
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8 article-container">
            <h1 class="article-title">{{ article.title }}</h1>
            <p class="article-meta">{{ article.create_data|date:"F j, Y" }} {{ article.author }}</p>
            <img src="{{ article.image.url }}" alt="{{ article.title }}" class="img-fluid my-3"> <!-- Make the image responsive -->
            <p class="article-description">{{ article.description }}</p>
            {% if messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <ul class="messages mb-0">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
            Izohlar:
            {% for comment in comments %}
                <div>
                    <p style="color: blue; font-weight: bold;">{{ comment.first_name }}</p>
                    <p style="font-style: italic;">{{ comment.text }}</p>
                </div>
                {% if comment.rating >= 1 %}
        <span>&#9733;
      {% endif %}
      {% if comment.rating >= 2 %}
        &#9733;
      {% endif %}
      {% if comment.rating >= 3 %}
        &#9733;
      {% endif %}
      {% if comment.rating >= 4 %}
        &#9733;
      {% endif %}
      {% if comment.rating == 5 %}
        &#9733;</span>
      {% endif %}
            {% endfor %}
            <form action="{% url 'article-detail' article.id %}" method="POST">
                {%csrf_token%}
                {{form.as_p}}
                <div class="rating-stars">
                    <input type="radio" name="rating" id="rs0" value="1"><label for="rs0"></label>
                    <input type="radio" name="rating" id="rs1" value="2"><label for="rs1"></label>
                    <input type="radio" name="rating" id="rs2" checked value="3"><label for="rs2"></label>
                    <input type="radio" name="rating" id="rs3" value="4"><label for="rs3"></label>
                    <input type="radio" name="rating" id="rs4" value="5"><label for="rs4"></label>
                    <span class="number"></span>
                </div>
                <button type="submit" class="btn btn-primary">Izoh qoldirish</button>

            </form>
            

            <a href="{% url 'articles-list' %}" class="btn btn-primary back-button">Asosiy sahifa</a>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

templates/create_article.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Maqola yaratish</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        /* Custom styles for better layout */
        body {
            background-color: #f8f9fa; /* Set background color */
            padding: 20px; /* Add padding for better spacing */
        }
        .article-container {
            max-width: 800px; /* Limit content width */
            margin: 0 auto; /* Center content */
            background-color: #fff; /* Set background color for article container */
            padding: 20px; /* Add padding */
            border-radius: 10px; /* Add border radius for rounded corners */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add box shadow for depth */
        }
        .article-title {
            font-size: 24px; /* Set title font size */
            color: #333; /* Set title color */
        }
        .article-description {
            font-size: 18px; /* Set description font size */
            color: #555; /* Set description color */
        }
        .back-button {
            margin-top: 20px; /* Add margin on top of button */
        }
    </style>
</head>
<body>

<div class="container">
    <div class="article-container">
        <h1 class="article-title">Maqola yaratish</h1>
        <form action="{% url 'create-article' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_title" class="form-label">Sarlavha:</label>
                {{ form.title }}
            </div>
            <div class="mb-3">
                <label for="id_description" class="form-label">Maqola matni:</label>
                {{ form.description }}
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Rasm:</label>
                {{ form.image }}
            </div>
            <button type="submit" class="btn btn-primary">Maqola yaratish</button>
        </form>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Articles</title>
    <style>
        /* Custom styles for better layout */
        .article-card {
            max-width: 300px; /* Limit card width */
        }
        .article-meta {
            font-size: 16px;
            color: #777;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <a href="{% url 'create-article' %}" class="btn btn-primary">Maqola yaratish</a>

    <div class="container mt-5">
        <h1 class="text-center mb-4">Maqolalar</h1>
        {% if messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <ul class="messages mb-0">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        <div class="d-flex flex-wrap justify-content-center">
            {% for article in articles %}
            <div class="card m-3 article-card">
                <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <p class="article-meta">{{ article.create_data|date:"F j, Y" }} </p>
                    <p class="card-text">{{ article.description|truncatewords:8 }}</p>
                    <a href="{% url 'article-detail' article.id %}" class="btn btn-primary">Maqolaga o'tish</a>
                </div>
            </div>
            {% endfor %}

        </div>

    </div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>